// AUTO-GENERATED by scripts/generate_curriculum.cjs
// Source of Truth: curriculumPlanner.json

export interface LessonMeta {
  id: string;
  title: string;
  order: number;
  prerequisites: string[];
  learning_goal: string[];
  key_terms: string[];
  content_file: string;
}

export interface CurriculumChapter {
  id: string;
  title: string;
  subtitle: string;
  metaphor: {
    title: string;
    description: string;
    imageAsset: string | null;
  };
  subConcepts: { id: string; name: string }[];
  lessons: LessonMeta[];
}

export const curriculumData: CurriculumChapter[] = [
  {
    "id": "ch-01",
    "title": "PM의 세계관과 역할",
    "subtitle": "Ch.1 — PM의 세계관과 역할",
    "metaphor": {
      "title": "PM의 세계관과 역할을(를) 쉽게 이해하기",
      "description": "PM의 세계관과 역할에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-01-ls-01",
        "name": "PM 직무 입문: 서비스와 PM의 본질"
      },
      {
        "id": "ch-01-ls-02",
        "name": "PM의 3대 핵심 마인드셋: 고객, 오너십, 피드백"
      },
      {
        "id": "ch-01-ls-03",
        "name": "이기는 팀의 커뮤니케이션: 논리적 소통과 신뢰"
      },
      {
        "id": "ch-01-ls-04",
        "name": "의사결정의 기술: 우선순위와 목표 관리"
      },
      {
        "id": "ch-01-ls-05",
        "name": "PM vs PJM vs PO: 정체성 확실히 하기"
      },
      {
        "id": "ch-01-ls-06",
        "name": "PM의 실무 도구와 역량 지도"
      },
      {
        "id": "ch-01-ls-07",
        "name": "성공하는 PM을 위한 커리어 로드맵"
      }
    ],
    "lessons": [
      {
        "id": "ch-01-ls-01",
        "title": "PM 직무 입문: 서비스와 PM의 본질",
        "order": 1,
        "prerequisites": [],
        "learning_goal": [
          "서비스의 정의를 이해한다",
          "PM이 해결해야 하는 근본적인 문제를 파악한다"
        ],
        "key_terms": [
          "프로덕트 매니저 (Product Manager)",
          "프로젝트 매니저 (Project Manager)"
        ],
        "content_file": "lessons/ch-01-ls-01.md"
      },
      {
        "id": "ch-01-ls-02",
        "title": "PM의 3대 핵심 마인드셋: 고객, 오너십, 피드백",
        "order": 2,
        "prerequisites": [
          "ch-01-ls-01"
        ],
        "learning_goal": [
          "고객 중심 사고의 중요성을 이해한다",
          "오너십과 성숙한 실리콘밸리 문화를 습득한다"
        ],
        "key_terms": [
          "고객 중심 사고 (Customer-Centric)",
          "문제 해결 (Problem Solving)",
          "오너십 (Ownership)",
          "심리적 안전감과 피드백 (Psychological Safety & Feedback)",
          "빠른 실패 (Fast Failure)"
        ],
        "content_file": "lessons/ch-01-ls-02.md"
      },
      {
        "id": "ch-01-ls-03",
        "title": "이기는 팀의 커뮤니케이션: 논리적 소통과 신뢰",
        "order": 3,
        "prerequisites": [
          "ch-01-ls-02"
        ],
        "learning_goal": [
          "개발자/디자이너와 신뢰를 구축하는 소통법을 배운다",
          "문서 기반의 논리적 소통(6-Pager)의 중요성을 이해한다"
        ],
        "key_terms": [
          "동기 부여와 참여 유도",
          "문제 해결사로서의 개발자",
          "1-Pager 및 PRD (제품 요구사항 정의서)",
          "솔직하고 보수적인 커뮤니케이션"
        ],
        "content_file": "lessons/ch-01-ls-03.md"
      },
      {
        "id": "ch-01-ls-04",
        "title": "의사결정의 기술: 우선순위와 목표 관리",
        "order": 4,
        "prerequisites": [
          "ch-01-ls-03"
        ],
        "learning_goal": [
          "RICE, MoSCoW 등 우선순위 프레임워크를 실무에 적용한다",
          "북극성 지표와 가설 검증의 중요성을 이해한다"
        ],
        "key_terms": [
          "Impact vs Effort 매트릭스 (가치 대비 노력 매트릭스)",
          "RICE 방법론",
          "MoSCoW 방법론",
          "북극성 지표 (North Star Metric)",
          "가설 검증과 MVP (Minimum Viable Product)"
        ],
        "content_file": "lessons/ch-01-ls-04.md"
      },
      {
        "id": "ch-01-ls-05",
        "title": "PM vs PJM vs PO: 정체성 확실히 하기",
        "order": 5,
        "prerequisites": [
          "ch-01-ls-01"
        ],
        "learning_goal": [
          "PM, PJM, PO의 역할 차이와 책임을 구분한다",
          "도메인과 조직 구조에 따른 역할 변화를 이해한다"
        ],
        "key_terms": [
          "프로덕트 매니저 (Product Manager)",
          "프로젝트 매니저 (Project Manager)",
          "프로덕트 오너 (Product Owner, PO)",
          "제품 비전과 우선순위화 (Prioritization)",
          "스코프 크립 (Scope Creep)"
        ],
        "content_file": "lessons/ch-01-ls-05.md"
      },
      {
        "id": "ch-01-ls-06",
        "title": "PM의 실무 도구와 역량 지도",
        "order": 6,
        "prerequisites": [
          "ch-01-ls-05"
        ],
        "learning_goal": [
          "PM이 사용하는 도구 리스트를 파악한다",
          "소프트 스킬과 하드 스킬의 균형을 이해한다"
        ],
        "key_terms": [
          "제품 요구사항 정의서 (PRD)",
          "성과 지표 (KPI/OKR)",
          "소프트 스킬 (Soft Skills)",
          "하드 스킬 (Hard Skills)",
          "프로젝트 관리 툴 (Jira, Asana 등)"
        ],
        "content_file": "lessons/ch-01-ls-06.md"
      },
      {
        "id": "ch-01-ls-07",
        "title": "성공하는 PM을 위한 커리어 로드맵",
        "order": 7,
        "prerequisites": [
          "ch-01-ls-06"
        ],
        "learning_goal": [
          "주니어 PM의 성장 팁과 실패를 대하는 태도를 배운다",
          "업계 선배들의 실전 팁을 체득한다"
        ],
        "key_terms": [
          "빠른 실행과 피드백 (Agile Execution)",
          "트렌드 캐칭 (Trend Catching)",
          "자기 PR과 스토리텔링 (Storytelling)",
          "실패에 대한 회복 탄력성 (Resilience)",
          "PM 경력 발전 패스 (Career Path)"
        ],
        "content_file": "lessons/ch-01-ls-07.md"
      }
    ]
  },
  {
    "id": "ch-02",
    "title": "PM 직무 심층 이해 (시니어 레슨)",
    "subtitle": "Ch.2 — PM 직무 심층 이해 (시니어 레슨)",
    "metaphor": {
      "title": "PM 직무 심층 이해 (시니어 레슨)을(를) 쉽게 이해하기",
      "description": "PM 직무 심층 이해 (시니어 레슨)에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-02-ls-01",
        "name": "시니어 PM 마스터클래스 입문"
      },
      {
        "id": "ch-02-ls-02",
        "name": "조직 구조와 채역 공고 역추적"
      },
      {
        "id": "ch-02-ls-03",
        "name": "고객 이해와 사용자 조사 기법"
      },
      {
        "id": "ch-02-ls-04",
        "name": "유저 저니 맵과 인지 부하 관리"
      },
      {
        "id": "ch-02-ls-05",
        "name": "데이터 기반 성장 지표 (AARRR/Funnel)"
      },
      {
        "id": "ch-02-ls-06",
        "name": "구현과 운영의 모범 사례"
      },
      {
        "id": "ch-02-ls-07",
        "name": "PM 학습 부록: 용어와 학습 플랜"
      }
    ],
    "lessons": [
      {
        "id": "ch-02-ls-01",
        "title": "시니어 PM 마스터클래스 입문",
        "order": 1,
        "prerequisites": [
          "ch-01-ls-07"
        ],
        "learning_goal": [
          "실무 개념 확장과 인덱스를 확인한다"
        ],
        "key_terms": [
          "PM (Product Manager)",
          "제품 지표 vs 프로젝트 지표",
          "기능 조직 vs 목적 조직"
        ],
        "content_file": "lessons/ch-02-ls-01.md"
      },
      {
        "id": "ch-02-ls-02",
        "title": "조직 구조와 채역 공고 역추적",
        "order": 2,
        "prerequisites": [
          "ch-02-ls-01"
        ],
        "learning_goal": [
          "기능 조직 vs 목적 조직의 차이를 안다",
          "채용 공고에서 요구 역량을 분석하는 법을 배운다"
        ],
        "key_terms": [
          "기능 조직 vs 목적 조직",
          "채용 공고에서 요구하는 PM 역량"
        ],
        "content_file": "lessons/ch-02-ls-02.md"
      },
      {
        "id": "ch-02-ls-03",
        "title": "고객 이해와 사용자 조사 기법",
        "order": 3,
        "prerequisites": [
          "ch-02-ls-02"
        ],
        "learning_goal": [
          "페르소나와 데스트 리서치의 실무 적용법을 익힌다",
          "고객 인터뷰(IDI)와 VOC 운영 전략을 배운다"
        ],
        "key_terms": [
          "페르소나 (Persona)",
          "데스크 리서치 (Desk Research)",
          "고객 인터뷰 (IDI)",
          "VOC 운영 (Voice of Customer)",
          "사용성 테스트 (UT)"
        ],
        "content_file": "lessons/ch-02-ls-03.md"
      },
      {
        "id": "ch-02-ls-04",
        "title": "유저 저니 맵과 인지 부하 관리",
        "order": 4,
        "prerequisites": [
          "ch-02-ls-03"
        ],
        "learning_goal": [
          "사용자 여정 지도를 그리고 페인포인트를 찾는다",
          "안티패턴을 통해 좋은 UX의 기준을 정립한다"
        ],
        "key_terms": [
          "유저 저니 맵 (User Journey Map)",
          "페인포인트 찾기와 가설 수립"
        ],
        "content_file": "lessons/ch-02-ls-04.md"
      },
      {
        "id": "ch-02-ls-05",
        "title": "데이터 기반 성장 지표 (AARRR/Funnel)",
        "order": 5,
        "prerequisites": [
          "ch-01-ls-04"
        ],
        "learning_goal": [
          "퍼널 분석과 AARRR 프레임워크를 이해한다",
          "핵심 제품 지표 세트를 설정하는 법을 배운다"
        ],
        "key_terms": [
          "퍼널 분석 (Funnel Analysis)",
          "AARRR (해적 지표)",
          "핵심 제품 지표 (MAU, Retention, LTV 등)",
          "히트맵 (Heatmap)",
          "레드 퀸 가설 (Red Queen hypothesis)"
        ],
        "content_file": "lessons/ch-02-ls-05.md"
      },
      {
        "id": "ch-02-ls-06",
        "title": "구현과 운영의 모범 사례",
        "order": 6,
        "prerequisites": [
          "ch-02-ls-05"
        ],
        "learning_goal": [
          "더블 다이아몬드, MVP, PRD 등 실무 산출물의 흐름을 익힌다"
        ],
        "key_terms": [
          "더블 다이아몬드 (Double Diamond)",
          "MVP (Minimum Viable Product)",
          "PRD (Product Requirements Document)",
          "IA (Information Architecture)",
          "유스 케이스 (Use Case)",
          "스토리보드 (Storyboard)",
          "프론트엔드와 백엔드 (Frontend / Backend)",
          "UI 구성요소 (UI Components)"
        ],
        "content_file": "lessons/ch-02-ls-06.md"
      },
      {
        "id": "ch-02-ls-07",
        "title": "PM 학습 부록: 용어와 학습 플랜",
        "order": 7,
        "prerequisites": [],
        "learning_goal": [
          "PM 용어 사전을 활용한다",
          "초심자용 2주 학습 플랜을 따른다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-02-ls-07.md"
      }
    ]
  },
  {
    "id": "ch-03",
    "title": "비즈니스 모델(BM) 설계",
    "subtitle": "Ch.3 — 비즈니스 모델(BM) 설계",
    "metaphor": {
      "title": "비즈니스 모델(BM) 설계을(를) 쉽게 이해하기",
      "description": "비즈니스 모델(BM) 설계에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-03-ls-01",
        "name": "비즈니스 모델의 본질과 기획 원칙 [특수 도메인 실습]"
      },
      {
        "id": "ch-03-ls-02",
        "name": "도메인 특화 BM 분석: 헬스케어와 메디컬 [특수 도메인 실습]"
      },
      {
        "id": "ch-03-ls-03",
        "name": "BM의 현대적 진화: BMC 3.0과 AI 도입 [특수 도메인 실습]"
      },
      {
        "id": "ch-03-ls-04",
        "name": "비즈니스 모델의 재무 설계: 수익화와 단위 경제학"
      },
      {
        "id": "ch-03-ls-05",
        "name": "수익성 지표와 가격 전략: 무비패스에서 쿠팡까지"
      }
    ],
    "lessons": [
      {
        "id": "ch-03-ls-01",
        "title": "비즈니스 모델의 본질과 기획 원칙 [특수 도메인 실습]",
        "order": 1,
        "prerequisites": [
          "ch-02-ls-07"
        ],
        "learning_goal": [
          "BM의 정의와 가치 제안(Value Proposition)을 이해한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-03-ls-01.md"
      },
      {
        "id": "ch-03-ls-02",
        "title": "도메인 특화 BM 분석: 헬스케어와 메디컬 [특수 도메인 실습]",
        "order": 2,
        "prerequisites": [
          "ch-03-ls-01"
        ],
        "learning_goal": [
          "도메인별 BM의 특성과 차이를 분석한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-03-ls-02.md"
      },
      {
        "id": "ch-03-ls-03",
        "title": "BM의 현대적 진화: BMC 3.0과 AI 도입 [특수 도메인 실습]",
        "order": 3,
        "prerequisites": [
          "ch-03-ls-02"
        ],
        "learning_goal": [
          "확장된 비즈니스 모델 캔버스(BMC 3.0)를 활용한다",
          "AI 도입이 BM 변화에 미치는 영향을 파악한다"
        ],
        "key_terms": [
          "가치 제안 (Value Proposition)",
          "비용 효과성 (Cost Effectiveness)",
          "기술적 제원 (Resources)",
          "AI 기반 비즈니스 모델",
          "모델 정합성 (Model Harmony)"
        ],
        "content_file": "lessons/ch-03-ls-03.md"
      },
      {
        "id": "ch-03-ls-04",
        "title": "비즈니스 모델의 재무 설계: 수익화와 단위 경제학",
        "order": 4,
        "prerequisites": [
          "ch-03-ls-03"
        ],
        "learning_goal": [
          "전략, BM, 수익화, 수익 모델의 위계를 이해한다",
          "린 캔버스와 BMC의 차이 및 RAT 검증법을 익힌다",
          "주요 수익화 모델 5가지의 특징을 파악한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-03-ls-04.md"
      },
      {
        "id": "ch-03-ls-05",
        "title": "수익성 지표와 가격 전략: 무비패스에서 쿠팡까지",
        "order": 5,
        "prerequisites": [
          "ch-03-ls-04"
        ],
        "learning_goal": [
          "LTV, CAC, NRR 등 핵심 단위 경제학 지표를 산출한다",
          "가격 책정을 위한 WTP 측정 기법을 배운다",
          "국내외 BM 성공 및 실패 사례의 핵심 원인을 분석한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-03-ls-05.md"
      }
    ]
  },
  {
    "id": "ch-04",
    "title": "기획 프로세스 실습",
    "subtitle": "Ch.4 — 기획 프로세스 실습",
    "metaphor": {
      "title": "기획 프로세스 실습을(를) 쉽게 이해하기",
      "description": "기획 프로세스 실습에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-04-ls-01",
        "name": "기획의 정석: Why-Who-What 프로세스"
      },
      {
        "id": "ch-04-ls-02",
        "name": "User Flow와 로직 명세 설계"
      },
      {
        "id": "ch-04-ls-03",
        "name": "기술 이해와 개발자 협업"
      },
      {
        "id": "ch-04-ls-04",
        "name": "MVP와 MLP: 무엇을 얼마나 만들 것인가"
      },
      {
        "id": "ch-04-ls-05",
        "name": "PMF와 그로스 지표: 제품이 시장에 맞는 순간"
      }
    ],
    "lessons": [
      {
        "id": "ch-04-ls-01",
        "title": "기획의 정석: Why-Who-What 프로세스",
        "order": 1,
        "prerequisites": [
          "ch-03-ls-05"
        ],
        "learning_goal": [
          "기획의 4단계 핵심 프로세스(Why → Who → What → How)의 흐름을 이해한다",
          "핵심 가설을 검증하기 위한 최소 완결 경험(MVP)의 올바른 정의를 이해한다"
        ],
        "key_terms": [
          "Why**: 우리가 이 서비스를 만드는 근본 이유 (해결하려는 문제)",
          "Who**: 이 문제를 가장 절실하게 겪는 구체적인 사람",
          "What**: 그 사람의 문제를 해결할 핵심 기능과 제공 가치",
          "How**: 그 가치를 실제로 어떻게 구현할 것인가",
          "MVP (Minimum Viable Product)**: 가설을 검증할 수 있는 최소한의 완결된 경험"
        ],
        "content_file": "lessons/ch-04-ls-01.md"
      },
      {
        "id": "ch-04-ls-02",
        "title": "User Flow와 로직 명세 설계",
        "order": 2,
        "prerequisites": [
          "ch-04-ls-01"
        ],
        "learning_goal": [
          "User Flow와 IA의 차이를 이해하고 예외/대체 경로(Alternate Flow)를 설계할 수 있다",
          "개발자가 코딩할 수 있는 수준의 화면 로직(디스크립션)을 작성할 수 있다"
        ],
        "key_terms": [
          "User Flow**: 사용자의 동선을 순서대로 그린 흐름도",
          "IA (Information Architecture)**: 서비스의 정보 구조 지도",
          "Happy Path**: 사용자가 오류 없이 목표를 달성하는 이상적 경로",
          "Alternate/Exception Flow**: 오류 상황이나 대안적 시나리오가 발생했을 때의 예외 경로 (속칭 Unhappy Path)",
          "디스크립션**: 화면설계서에서 화면의 동작 로직을 텍스트로 설명한 것"
        ],
        "content_file": "lessons/ch-04-ls-02.md"
      },
      {
        "id": "ch-04-ls-03",
        "title": "기술 이해와 개발자 협업",
        "order": 3,
        "prerequisites": [
          "ch-04-ls-02"
        ],
        "learning_goal": [
          "사용자가 직면할 수 있는 4대 상태(Ideal/Empty/Loading/Error)를 설계한다",
          "앱/웹 환경에서의 Skeleton UI 개념과 네트워크 로딩 응답 대응 지침을 안다",
          "일정과 인력 리소스에 맞춘 기술적 실현 가능성(Feasibility) 및 스펙 아웃 전략을 이해한다"
        ],
        "key_terms": [
          "4대 상태**: Ideal, Empty, Loading, Error로 구분되는 화면의 주기 상태",
          "Skeleton UI**: 콘텐츠가 로드되기 전 실제 레이아웃과 동일한 모양의 회색 뼈대를 렌더링하는 UI",
          "Feasibility (실현 가능성)**: \"이 기획이 기술적으로 구현 가능하며, 주어진 기간과 인원으로 구축할 수 있는가?\"",
          "스펙 아웃 (Spec-out)**: 리소스/일정 조건에 따라 덜 중요한 기능을 의식적으로 범위 밖으로 빼는 결정"
        ],
        "content_file": "lessons/ch-04-ls-03.md"
      },
      {
        "id": "ch-04-ls-04",
        "title": "MVP와 MLP: 무엇을 얼마나 만들 것인가",
        "order": 4,
        "prerequisites": [
          "ch-04-ls-03"
        ],
        "learning_goal": [
          "MVP와 MLP의 차이를 이해하고 사랑받는 최소 제품을 정의한다",
          "Prototype, PoC, V1의 목적과 활용 시점을 구분한다",
          "최소 완결 경험(MVP)을 위한 실무 체크리스트를 활용한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-04-ls-04.md"
      },
      {
        "id": "ch-04-ls-05",
        "title": "PMF와 그로스 지표: 제품이 시장에 맞는 순간",
        "order": 5,
        "prerequisites": [
          "ch-04-ls-04"
        ],
        "learning_goal": [
          "PMF(Product-Market Fit)의 신호와 검증 지표를 파악한다",
          "북극성 지표(NSM) 설정 기준과 A/B 테스트 실무를 익힌다",
          "Must-have와 Nice-to-have를 가려내는 실무 질문을 적용한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-04-ls-05.md"
      }
    ]
  },
  {
    "id": "ch-05",
    "title": "실행과 통제: 애자일(Agile)",
    "subtitle": "Ch.5 — 실행과 통제: 애자일(Agile)",
    "metaphor": {
      "title": "실행과 통제: 애자일(Agile)을(를) 쉽게 이해하기",
      "description": "실행과 통제: 애자일(Agile)에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-05-ls-01",
        "name": "백로그 관리와 우선순위 프레임워크"
      },
      {
        "id": "ch-05-ls-02",
        "name": "스크럼 실무: 스토리 포인트와 일정 방어"
      },
      {
        "id": "ch-05-ls-03",
        "name": "출시와 회고: KPT와 블레임리스 포스트모템"
      }
    ],
    "lessons": [
      {
        "id": "ch-05-ls-01",
        "title": "백로그 관리와 우선순위 프레임워크",
        "order": 1,
        "prerequisites": [
          "ch-01-ls-04"
        ],
        "learning_goal": [
          "백로그의 정의와 RICE, MoSCoW, 아이젠하워 매트릭스를 복습/심화한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-05-ls-01.md"
      },
      {
        "id": "ch-05-ls-02",
        "title": "스크럼 실무: 스토리 포인트와 일정 방어",
        "order": 2,
        "prerequisites": [
          "ch-05-ls-01"
        ],
        "learning_goal": [
          "스토리 포인트, 벨로시티, 데일리 스크럼, 백로그 그루밍을 배운다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-05-ls-02.md"
      },
      {
        "id": "ch-05-ls-03",
        "title": "출시와 회고: KPT와 블레임리스 포스트모템",
        "order": 3,
        "prerequisites": [
          "ch-05-ls-02"
        ],
        "learning_goal": [
          "QA/Feature Flag 중심의 배포 전 통제를 배운다",
          "KPT 회고와 비난 없는 포스트모템 문화를 익힌다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-05-ls-03.md"
      }
    ]
  },
  {
    "id": "ch-06",
    "title": "미래 시프트: 데이터와 AI",
    "subtitle": "Ch.6 — 미래 시프트: 데이터와 AI",
    "metaphor": {
      "title": "미래 시프트: 데이터와 AI을(를) 쉽게 이해하기",
      "description": "미래 시프트: 데이터와 AI에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-06-ls-01",
        "name": "데이터 리터러시: SQL부터 코호트까지"
      },
      {
        "id": "ch-06-ls-02",
        "name": "AI 시대의 핵심 무기: 판단력과 바이브 코딩"
      },
      {
        "id": "ch-06-ls-03",
        "name": "AI 전략 회의실: 입체적 분석과 최종 합의"
      }
    ],
    "lessons": [
      {
        "id": "ch-06-ls-01",
        "title": "데이터 리터러시: SQL부터 코호트까지",
        "order": 1,
        "prerequisites": [
          "ch-02-ls-05"
        ],
        "learning_goal": [
          "실전 SQL 기초, 이벤트 로깅(Taxonomy), 코호트 분석을 배운다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-06-ls-01.md"
      },
      {
        "id": "ch-06-ls-02",
        "title": "AI 시대의 핵심 무기: 판단력과 바이브 코딩",
        "order": 2,
        "prerequisites": [
          "ch-04-ls-03"
        ],
        "learning_goal": [
          "도메인 전문성과 판단력의 가치를 안다",
          "바이브 코딩과 에이전트 활용법을 익힌다"
        ],
        "key_terms": [
          "가장 강력한 찬성 논거 1가지",
          "가장 뼈아픈 반대 논거 1가지",
          "'사람 간의 관계성'",
          "\"내가 무엇을 원하는지 아는 것\"",
          "'판단력(Judgment)'",
          "'나를 이해하는 힘(자기 객관화)'"
        ],
        "content_file": "lessons/ch-06-ls-02.md"
      },
      {
        "id": "ch-06-ls-03",
        "title": "AI 전략 회의실: 입체적 분석과 최종 합의",
        "order": 3,
        "prerequisites": [
          "ch-06-ls-02"
        ],
        "learning_goal": [
          "전문가 페르소나 설정과 망하는 길 찾기(역발상)를 실습한다",
          "다각도 토론 결과를 바탕으로 최종 개선안을 도출한다"
        ],
        "key_terms": [],
        "content_file": "lessons/ch-06-ls-03.md"
      }
    ]
  },
  {
    "id": "ch-07",
    "title": "마스터클래스 총결산",
    "subtitle": "Ch.7 — 마스터클래스 총결산",
    "metaphor": {
      "title": "마스터클래스 총결산을(를) 쉽게 이해하기",
      "description": "마스터클래스 총결산에 대한 핵심 개념을 살펴봅니다.",
      "imageAsset": null
    },
    "subConcepts": [
      {
        "id": "ch-07-ls-01",
        "name": "제품의 탄생부터 성장까지: 통합 리뷰"
      }
    ],
    "lessons": [
      {
        "id": "ch-07-ls-01",
        "title": "제품의 탄생부터 성장까지: 통합 리뷰",
        "order": 1,
        "prerequisites": [
          "ch-06-ls-03"
        ],
        "learning_goal": [
          "전체 커리큘럼의 핵심 맥락을 관통하는 내용을 복습한다"
        ],
        "key_terms": [
          "PM (Product Manager)",
          "PJM (Project Manager)",
          "PO (Product Owner)",
          "기능 조직 vs 목적 조직",
          "User Persona",
          "User Journey Map",
          "AARRR (퍼널 프레임워크)",
          "Double Diamond (더블 다이아몬드)"
        ],
        "content_file": "lessons/ch-07-ls-01.md"
      }
    ]
  }
];

export default curriculumData;
