Write-Output "Designer Output"
Write-Output "- Visual goal:"
Write-Output "- Motion mapping:"
Write-Output "- Accessibility/perf notes:"
Write-Output ""
Write-Output "PM Output"
Write-Output "- Problem statement:"
Write-Output "- KPI:"
Write-Output "- Scope / Non-goals:"
Write-Output ""
Write-Output "FE Output"
Write-Output "- Architecture:"
Write-Output "- Component plan:"
Write-Output "- Motion fallback:"
Write-Output ""
Write-Output "Merged Decision"
Write-Output "- Final direction:"
Write-Output "- Tradeoffs:"
Write-Output ""
Write-Output "Acceptance Checklist"
Write-Output "- [ ] Learning clarity validated"
Write-Output "- [ ] Accessibility baseline met"
Write-Output "- [ ] Performance constraints met"
